# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EtixAvailablePricesSchema(BaseModel):
    """
    EtixAvailablePricesSchema
    """ # noqa: E501
    place_id: StrictStr
    price_level_id: Optional[StrictStr]
    price_code_name: Optional[StrictStr]
    max_quantity: Optional[StrictInt]
    total_price: Optional[StrictStr]
    section: StrictStr
    row: StrictStr
    seat: StrictStr
    row_rank: Optional[StrictInt]
    seat_rank: Optional[StrictInt]
    __properties: ClassVar[List[str]] = ["place_id", "price_level_id", "price_code_name", "max_quantity", "total_price", "section", "row", "seat", "row_rank", "seat_rank"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EtixAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price_level_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_level_id is None and "price_level_id" in self.model_fields_set:
            _dict['price_level_id'] = None

        # set to None if price_code_name (nullable) is None
        # and model_fields_set contains the field
        if self.price_code_name is None and "price_code_name" in self.model_fields_set:
            _dict['price_code_name'] = None

        # set to None if max_quantity (nullable) is None
        # and model_fields_set contains the field
        if self.max_quantity is None and "max_quantity" in self.model_fields_set:
            _dict['max_quantity'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        # set to None if row_rank (nullable) is None
        # and model_fields_set contains the field
        if self.row_rank is None and "row_rank" in self.model_fields_set:
            _dict['row_rank'] = None

        # set to None if seat_rank (nullable) is None
        # and model_fields_set contains the field
        if self.seat_rank is None and "seat_rank" in self.model_fields_set:
            _dict['seat_rank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EtixAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "price_level_id": obj.get("price_level_id"),
            "price_code_name": obj.get("price_code_name"),
            "max_quantity": obj.get("max_quantity"),
            "total_price": obj.get("total_price"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seat": obj.get("seat"),
            "row_rank": obj.get("row_rank"),
            "seat_rank": obj.get("seat_rank")
        })
        return _obj


