# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EtixUpdateItemSchema(str, Enum):
    """
    EtixUpdateItemSchema
    """

    """
    allowed enum values
    """
    PRICE_LEVEL_ID = 'PRICE_LEVEL_ID'
    PRICE_CODE_NAME = 'PRICE_CODE_NAME'
    MAX_QUANTITY = 'MAX_QUANTITY'
    TOTAL_PRICE = 'TOTAL_PRICE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EtixUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


