# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.listprice import Listprice
from listing_data_storage_client.models.ticketmaster_update_item_schema import TicketmasterUpdateItemSchema
from listing_data_storage_client.models.totalprice import Totalprice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListingPriceSeatStoreSchema(BaseModel):
    """
    ListingPriceSeatStoreSchema
    """ # noqa: E501
    place_id: StrictStr = Field(alias="placeId")
    list_price: Optional[Listprice] = Field(default=None, alias="listPrice")
    total_price: Optional[Totalprice] = Field(default=None, alias="totalPrice")
    update_items: Optional[List[TicketmasterUpdateItemSchema]] = Field(default=None, alias="updateItems")
    __properties: ClassVar[List[str]] = ["placeId", "listPrice", "totalPrice", "updateItems"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListingPriceSeatStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of list_price
        if self.list_price:
            _dict['listPrice'] = self.list_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['totalPrice'] = self.total_price.to_dict()
        # set to None if list_price (nullable) is None
        # and model_fields_set contains the field
        if self.list_price is None and "list_price" in self.model_fields_set:
            _dict['listPrice'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['totalPrice'] = None

        # set to None if update_items (nullable) is None
        # and model_fields_set contains the field
        if self.update_items is None and "update_items" in self.model_fields_set:
            _dict['updateItems'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListingPriceSeatStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "placeId": obj.get("placeId"),
            "listPrice": Listprice.from_dict(obj["listPrice"]) if obj.get("listPrice") is not None else None,
            "totalPrice": Totalprice.from_dict(obj["totalPrice"]) if obj.get("totalPrice") is not None else None,
            "updateItems": obj.get("updateItems")
        })
        return _obj


