# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MpvUpdateItemSchema(str, Enum):
    """
    MpvUpdateItemSchema
    """

    """
    allowed enum values
    """
    PRICE = 'PRICE'
    TOTAL_PRICE = 'TOTAL_PRICE'
    SERVICE_CHARGE = 'SERVICE_CHARGE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MpvUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


