# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.mpv_update_item_schema import MpvUpdateItemSchema
from listing_data_storage_client.models.price import Price
from listing_data_storage_client.models.service_charge import ServiceCharge
from listing_data_storage_client.models.total_price import TotalPrice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MpvPriceStoreSchema(BaseModel):
    """
    MpvPriceStoreSchema
    """ # noqa: E501
    place_id: StrictStr
    price: Optional[Price] = None
    total_price: Optional[TotalPrice] = None
    service_charge: Optional[ServiceCharge] = None
    update_items: Optional[List[MpvUpdateItemSchema]] = None
    __properties: ClassVar[List[str]] = ["place_id", "price", "total_price", "service_charge", "update_items"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MpvPriceStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_charge
        if self.service_charge:
            _dict['service_charge'] = self.service_charge.to_dict()
        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        # set to None if service_charge (nullable) is None
        # and model_fields_set contains the field
        if self.service_charge is None and "service_charge" in self.model_fields_set:
            _dict['service_charge'] = None

        # set to None if update_items (nullable) is None
        # and model_fields_set contains the field
        if self.update_items is None and "update_items" in self.model_fields_set:
            _dict['update_items'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MpvPriceStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "price": Price.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "total_price": TotalPrice.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None,
            "service_charge": ServiceCharge.from_dict(obj["service_charge"]) if obj.get("service_charge") is not None else None,
            "update_items": obj.get("update_items")
        })
        return _obj


