# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from listing_data_storage_client.models.base_price import BasePrice
from listing_data_storage_client.models.fees import Fees
from listing_data_storage_client.models.total_price1 import TotalPrice1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OvationtixStoreSchema(BaseModel):
    """
    OvationtixStoreSchema
    """ # noqa: E501
    place_id: StrictStr
    section: StrictStr
    row: StrictStr
    row_rank: StrictInt
    seat_number: StrictStr
    seat_rank: StrictInt
    total_price: TotalPrice1
    price_level: StrictStr
    attributes: StrictStr
    description: StrictStr
    delivery_method: StrictStr
    base_price: BasePrice
    fees: Fees
    __properties: ClassVar[List[str]] = ["place_id", "section", "row", "row_rank", "seat_number", "seat_rank", "total_price", "price_level", "attributes", "description", "delivery_method", "base_price", "fees"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OvationtixStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of base_price
        if self.base_price:
            _dict['base_price'] = self.base_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fees
        if self.fees:
            _dict['fees'] = self.fees.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OvationtixStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "row_rank": obj.get("row_rank"),
            "seat_number": obj.get("seat_number"),
            "seat_rank": obj.get("seat_rank"),
            "total_price": TotalPrice1.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None,
            "price_level": obj.get("price_level"),
            "attributes": obj.get("attributes"),
            "description": obj.get("description"),
            "delivery_method": obj.get("delivery_method"),
            "base_price": BasePrice.from_dict(obj["base_price"]) if obj.get("base_price") is not None else None,
            "fees": Fees.from_dict(obj["fees"]) if obj.get("fees") is not None else None
        })
        return _obj


