# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaciolanAvailablePricesSchema(BaseModel):
    """
    PaciolanAvailablePricesSchema
    """ # noqa: E501
    price_level_id: StrictStr
    price_level_secname: StrictStr
    price_min: StrictStr
    price_max: StrictStr
    facility_fee_max: Optional[StrictStr]
    facility_fee_min: Optional[StrictStr]
    facility_tiered_fee_min: Optional[StrictStr]
    facility_tiered_fee_max: Optional[StrictStr]
    per_ticket_fee_min: Optional[StrictStr]
    per_ticket_fee_max: Optional[StrictStr]
    per_ticket_fee_min_tiered: Optional[StrictStr]
    per_ticket_fee_max_tiered: Optional[StrictStr]
    place_id: StrictStr
    total_price: StrictStr
    __properties: ClassVar[List[str]] = ["price_level_id", "price_level_secname", "price_min", "price_max", "facility_fee_max", "facility_fee_min", "facility_tiered_fee_min", "facility_tiered_fee_max", "per_ticket_fee_min", "per_ticket_fee_max", "per_ticket_fee_min_tiered", "per_ticket_fee_max_tiered", "place_id", "total_price"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaciolanAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if facility_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.facility_fee_max is None and "facility_fee_max" in self.model_fields_set:
            _dict['facility_fee_max'] = None

        # set to None if facility_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.facility_fee_min is None and "facility_fee_min" in self.model_fields_set:
            _dict['facility_fee_min'] = None

        # set to None if facility_tiered_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.facility_tiered_fee_min is None and "facility_tiered_fee_min" in self.model_fields_set:
            _dict['facility_tiered_fee_min'] = None

        # set to None if facility_tiered_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.facility_tiered_fee_max is None and "facility_tiered_fee_max" in self.model_fields_set:
            _dict['facility_tiered_fee_max'] = None

        # set to None if per_ticket_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_min is None and "per_ticket_fee_min" in self.model_fields_set:
            _dict['per_ticket_fee_min'] = None

        # set to None if per_ticket_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_max is None and "per_ticket_fee_max" in self.model_fields_set:
            _dict['per_ticket_fee_max'] = None

        # set to None if per_ticket_fee_min_tiered (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_min_tiered is None and "per_ticket_fee_min_tiered" in self.model_fields_set:
            _dict['per_ticket_fee_min_tiered'] = None

        # set to None if per_ticket_fee_max_tiered (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_max_tiered is None and "per_ticket_fee_max_tiered" in self.model_fields_set:
            _dict['per_ticket_fee_max_tiered'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaciolanAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "price_level_id": obj.get("price_level_id"),
            "price_level_secname": obj.get("price_level_secname"),
            "price_min": obj.get("price_min"),
            "price_max": obj.get("price_max"),
            "facility_fee_max": obj.get("facility_fee_max"),
            "facility_fee_min": obj.get("facility_fee_min"),
            "facility_tiered_fee_min": obj.get("facility_tiered_fee_min"),
            "facility_tiered_fee_max": obj.get("facility_tiered_fee_max"),
            "per_ticket_fee_min": obj.get("per_ticket_fee_min"),
            "per_ticket_fee_max": obj.get("per_ticket_fee_max"),
            "per_ticket_fee_min_tiered": obj.get("per_ticket_fee_min_tiered"),
            "per_ticket_fee_max_tiered": obj.get("per_ticket_fee_max_tiered"),
            "place_id": obj.get("place_id"),
            "total_price": obj.get("total_price")
        })
        return _obj


