# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaciolanAvailableDetailedSchema(BaseModel):
    """
    PaciolanAvailableDetailedSchema
    """ # noqa: E501
    place_id: StrictStr
    section: StrictStr
    row: StrictStr
    seat_number: Optional[StrictStr]
    event_id: StrictStr
    seat_type: Optional[StrictStr]
    price_level_secname: Optional[StrictStr]
    price_min: Optional[StrictStr]
    price_max: Optional[StrictStr]
    facility_fee_min: Optional[StrictStr]
    facility_fee_max: Optional[StrictStr]
    facility_tiered_fee_min: Optional[StrictStr]
    facility_tiered_fee_max: Optional[StrictStr]
    per_ticket_fee_min: Optional[StrictStr]
    per_ticket_fee_max: Optional[StrictStr]
    per_ticket_fee_min_tiered: Optional[StrictStr]
    per_ticket_fee_max_tiered: Optional[StrictStr]
    total_price: Optional[StrictStr]
    inserted: datetime
    __properties: ClassVar[List[str]] = ["place_id", "section", "row", "seat_number", "event_id", "seat_type", "price_level_secname", "price_min", "price_max", "facility_fee_min", "facility_fee_max", "facility_tiered_fee_min", "facility_tiered_fee_max", "per_ticket_fee_min", "per_ticket_fee_max", "per_ticket_fee_min_tiered", "per_ticket_fee_max_tiered", "total_price", "inserted"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaciolanAvailableDetailedSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if seat_number (nullable) is None
        # and model_fields_set contains the field
        if self.seat_number is None and "seat_number" in self.model_fields_set:
            _dict['seat_number'] = None

        # set to None if seat_type (nullable) is None
        # and model_fields_set contains the field
        if self.seat_type is None and "seat_type" in self.model_fields_set:
            _dict['seat_type'] = None

        # set to None if price_level_secname (nullable) is None
        # and model_fields_set contains the field
        if self.price_level_secname is None and "price_level_secname" in self.model_fields_set:
            _dict['price_level_secname'] = None

        # set to None if price_min (nullable) is None
        # and model_fields_set contains the field
        if self.price_min is None and "price_min" in self.model_fields_set:
            _dict['price_min'] = None

        # set to None if price_max (nullable) is None
        # and model_fields_set contains the field
        if self.price_max is None and "price_max" in self.model_fields_set:
            _dict['price_max'] = None

        # set to None if facility_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.facility_fee_min is None and "facility_fee_min" in self.model_fields_set:
            _dict['facility_fee_min'] = None

        # set to None if facility_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.facility_fee_max is None and "facility_fee_max" in self.model_fields_set:
            _dict['facility_fee_max'] = None

        # set to None if facility_tiered_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.facility_tiered_fee_min is None and "facility_tiered_fee_min" in self.model_fields_set:
            _dict['facility_tiered_fee_min'] = None

        # set to None if facility_tiered_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.facility_tiered_fee_max is None and "facility_tiered_fee_max" in self.model_fields_set:
            _dict['facility_tiered_fee_max'] = None

        # set to None if per_ticket_fee_min (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_min is None and "per_ticket_fee_min" in self.model_fields_set:
            _dict['per_ticket_fee_min'] = None

        # set to None if per_ticket_fee_max (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_max is None and "per_ticket_fee_max" in self.model_fields_set:
            _dict['per_ticket_fee_max'] = None

        # set to None if per_ticket_fee_min_tiered (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_min_tiered is None and "per_ticket_fee_min_tiered" in self.model_fields_set:
            _dict['per_ticket_fee_min_tiered'] = None

        # set to None if per_ticket_fee_max_tiered (nullable) is None
        # and model_fields_set contains the field
        if self.per_ticket_fee_max_tiered is None and "per_ticket_fee_max_tiered" in self.model_fields_set:
            _dict['per_ticket_fee_max_tiered'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaciolanAvailableDetailedSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seat_number": obj.get("seat_number"),
            "event_id": obj.get("event_id"),
            "seat_type": obj.get("seat_type"),
            "price_level_secname": obj.get("price_level_secname"),
            "price_min": obj.get("price_min"),
            "price_max": obj.get("price_max"),
            "facility_fee_min": obj.get("facility_fee_min"),
            "facility_fee_max": obj.get("facility_fee_max"),
            "facility_tiered_fee_min": obj.get("facility_tiered_fee_min"),
            "facility_tiered_fee_max": obj.get("facility_tiered_fee_max"),
            "per_ticket_fee_min": obj.get("per_ticket_fee_min"),
            "per_ticket_fee_max": obj.get("per_ticket_fee_max"),
            "per_ticket_fee_min_tiered": obj.get("per_ticket_fee_min_tiered"),
            "per_ticket_fee_max_tiered": obj.get("per_ticket_fee_max_tiered"),
            "total_price": obj.get("total_price"),
            "inserted": obj.get("inserted")
        })
        return _obj


