# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.paciolan_available_detailed_schema import PaciolanAvailableDetailedSchema
from listing_data_storage_client.models.paciolan_available_ga_detailed_schema import PaciolanAvailableGaDetailedSchema
from typing import Optional, Set
from typing_extensions import Self

class PaciolanAvailableDetailedResponseSchema(BaseModel):
    """
    PaciolanAvailableDetailedResponseSchema
    """ # noqa: E501
    available_places: Optional[List[PaciolanAvailableDetailedSchema]] = None
    available_ga_places: Optional[List[PaciolanAvailableGaDetailedSchema]] = None
    __properties: ClassVar[List[str]] = ["available_places", "available_ga_places"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaciolanAvailableDetailedResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_places (list)
        _items = []
        if self.available_places:
            for _item_available_places in self.available_places:
                if _item_available_places:
                    _items.append(_item_available_places.to_dict())
            _dict['available_places'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_ga_places (list)
        _items = []
        if self.available_ga_places:
            for _item_available_ga_places in self.available_ga_places:
                if _item_available_ga_places:
                    _items.append(_item_available_ga_places.to_dict())
            _dict['available_ga_places'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaciolanAvailableDetailedResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available_places": [PaciolanAvailableDetailedSchema.from_dict(_item) for _item in obj["available_places"]] if obj.get("available_places") is not None else None,
            "available_ga_places": [PaciolanAvailableGaDetailedSchema.from_dict(_item) for _item in obj["available_ga_places"]] if obj.get("available_ga_places") is not None else None
        })
        return _obj


