# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.paciolan_ga_section_store_schema import PaciolanGaSectionStoreSchema
from listing_data_storage_client.models.paciolan_seat_store_schema import PaciolanSeatStoreSchema
from listing_data_storage_client.models.update_paciolan_seat_store_schema import UpdatePaciolanSeatStoreSchema
from typing import Optional, Set
from typing_extensions import Self

class PaciolanStoreRequestSchema(BaseModel):
    """
    PaciolanStoreRequestSchema
    """ # noqa: E501
    message_id: StrictStr = Field(alias="messageId")
    venue_id: StrictStr = Field(alias="venueId")
    event_id: StrictStr = Field(alias="eventId")
    event_timestamp: datetime = Field(alias="eventTimestamp")
    full_update: StrictBool = Field(alias="fullUpdate")
    update: Optional[UpdatePaciolanSeatStoreSchema] = None
    seats: List[PaciolanSeatStoreSchema]
    ga_section: Optional[List[PaciolanGaSectionStoreSchema]] = None
    __properties: ClassVar[List[str]] = ["messageId", "venueId", "eventId", "eventTimestamp", "fullUpdate", "update", "seats", "ga_section"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaciolanStoreRequestSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of update
        if self.update:
            _dict['update'] = self.update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in seats (list)
        _items = []
        if self.seats:
            for _item_seats in self.seats:
                if _item_seats:
                    _items.append(_item_seats.to_dict())
            _dict['seats'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ga_section (list)
        _items = []
        if self.ga_section:
            for _item_ga_section in self.ga_section:
                if _item_ga_section:
                    _items.append(_item_ga_section.to_dict())
            _dict['ga_section'] = _items
        # set to None if update (nullable) is None
        # and model_fields_set contains the field
        if self.update is None and "update" in self.model_fields_set:
            _dict['update'] = None

        # set to None if ga_section (nullable) is None
        # and model_fields_set contains the field
        if self.ga_section is None and "ga_section" in self.model_fields_set:
            _dict['ga_section'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaciolanStoreRequestSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messageId": obj.get("messageId"),
            "venueId": obj.get("venueId"),
            "eventId": obj.get("eventId"),
            "eventTimestamp": obj.get("eventTimestamp"),
            "fullUpdate": obj.get("fullUpdate"),
            "update": UpdatePaciolanSeatStoreSchema.from_dict(obj["update"]) if obj.get("update") is not None else None,
            "seats": [PaciolanSeatStoreSchema.from_dict(_item) for _item in obj["seats"]] if obj.get("seats") is not None else None,
            "ga_section": [PaciolanGaSectionStoreSchema.from_dict(_item) for _item in obj["ga_section"]] if obj.get("ga_section") is not None else None
        })
        return _obj


