# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.price1 import Price1
from listing_data_storage_client.models.vividseats_update_item_schema import VividseatsUpdateItemSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PriceSeatStoreSchema(BaseModel):
    """
    PriceSeatStoreSchema
    """ # noqa: E501
    place_id: StrictStr = Field(alias="placeId")
    price: Price1
    quantity: StrictInt
    sellable_quantities: List[StrictInt] = Field(alias="sellableQuantities")
    update_items: Optional[List[VividseatsUpdateItemSchema]] = Field(default=None, alias="updateItems")
    __properties: ClassVar[List[str]] = ["placeId", "price", "quantity", "sellableQuantities", "updateItems"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PriceSeatStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # set to None if update_items (nullable) is None
        # and model_fields_set contains the field
        if self.update_items is None and "update_items" in self.model_fields_set:
            _dict['updateItems'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PriceSeatStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "placeId": obj.get("placeId"),
            "price": Price1.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "quantity": obj.get("quantity"),
            "sellableQuantities": obj.get("sellableQuantities"),
            "updateItems": obj.get("updateItems")
        })
        return _obj


