# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.deal_score import DealScore
from listing_data_storage_client.models.fee import Fee
from listing_data_storage_client.models.seatgeek_update_item_schema import SeatgeekUpdateItemSchema
from listing_data_storage_client.models.ticket_price import TicketPrice
from listing_data_storage_client.models.total_price import TotalPrice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SeatgeekStoreSchema(BaseModel):
    """
    SeatgeekStoreSchema
    """ # noqa: E501
    listing_id: StrictStr
    ticket_price: Optional[TicketPrice] = None
    fee: Optional[Fee] = None
    total_price: Optional[TotalPrice] = None
    deal_score: Optional[DealScore] = None
    update_items: Optional[List[SeatgeekUpdateItemSchema]] = None
    section: Optional[StrictStr] = None
    row: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    row_rank: Optional[StrictInt] = None
    seat: Optional[StrictStr] = None
    seat_rank: Optional[StrictInt] = None
    quantity: Optional[StrictInt] = 1
    delivery_type: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["listing_id", "ticket_price", "fee", "total_price", "deal_score", "update_items", "section", "row", "slug", "row_rank", "seat", "seat_rank", "quantity", "delivery_type", "notes", "description"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SeatgeekStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ticket_price
        if self.ticket_price:
            _dict['ticket_price'] = self.ticket_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fee
        if self.fee:
            _dict['fee'] = self.fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deal_score
        if self.deal_score:
            _dict['deal_score'] = self.deal_score.to_dict()
        # set to None if ticket_price (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_price is None and "ticket_price" in self.model_fields_set:
            _dict['ticket_price'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        # set to None if deal_score (nullable) is None
        # and model_fields_set contains the field
        if self.deal_score is None and "deal_score" in self.model_fields_set:
            _dict['deal_score'] = None

        # set to None if update_items (nullable) is None
        # and model_fields_set contains the field
        if self.update_items is None and "update_items" in self.model_fields_set:
            _dict['update_items'] = None

        # set to None if section (nullable) is None
        # and model_fields_set contains the field
        if self.section is None and "section" in self.model_fields_set:
            _dict['section'] = None

        # set to None if row (nullable) is None
        # and model_fields_set contains the field
        if self.row is None and "row" in self.model_fields_set:
            _dict['row'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if row_rank (nullable) is None
        # and model_fields_set contains the field
        if self.row_rank is None and "row_rank" in self.model_fields_set:
            _dict['row_rank'] = None

        # set to None if seat (nullable) is None
        # and model_fields_set contains the field
        if self.seat is None and "seat" in self.model_fields_set:
            _dict['seat'] = None

        # set to None if seat_rank (nullable) is None
        # and model_fields_set contains the field
        if self.seat_rank is None and "seat_rank" in self.model_fields_set:
            _dict['seat_rank'] = None

        # set to None if delivery_type (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_type is None and "delivery_type" in self.model_fields_set:
            _dict['delivery_type'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SeatgeekStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "listing_id": obj.get("listing_id"),
            "ticket_price": TicketPrice.from_dict(obj["ticket_price"]) if obj.get("ticket_price") is not None else None,
            "fee": Fee.from_dict(obj["fee"]) if obj.get("fee") is not None else None,
            "total_price": TotalPrice.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None,
            "deal_score": DealScore.from_dict(obj["deal_score"]) if obj.get("deal_score") is not None else None,
            "update_items": obj.get("update_items"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "slug": obj.get("slug"),
            "row_rank": obj.get("row_rank"),
            "seat": obj.get("seat"),
            "seat_rank": obj.get("seat_rank"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "delivery_type": obj.get("delivery_type"),
            "notes": obj.get("notes"),
            "description": obj.get("description")
        })
        return _obj


