# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from listing_data_storage_client.models.seats import Seats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SeatSoldSchema(BaseModel):
    """
    SeatSoldSchema
    """ # noqa: E501
    section: StrictStr
    row: Optional[StrictStr]
    seats: Seats
    quantity: Annotated[int, Field(strict=True, ge=0)]
    sold_time: datetime
    price: StrictStr
    total_available: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    total_capacity: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["section", "row", "seats", "quantity", "sold_time", "price", "total_available", "total_capacity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SeatSoldSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of seats
        if self.seats:
            _dict['seats'] = self.seats.to_dict()
        # set to None if row (nullable) is None
        # and model_fields_set contains the field
        if self.row is None and "row" in self.model_fields_set:
            _dict['row'] = None

        # set to None if total_available (nullable) is None
        # and model_fields_set contains the field
        if self.total_available is None and "total_available" in self.model_fields_set:
            _dict['total_available'] = None

        # set to None if total_capacity (nullable) is None
        # and model_fields_set contains the field
        if self.total_capacity is None and "total_capacity" in self.model_fields_set:
            _dict['total_capacity'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SeatSoldSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seats": Seats.from_dict(obj["seats"]) if obj.get("seats") is not None else None,
            "quantity": obj.get("quantity"),
            "sold_time": obj.get("sold_time"),
            "price": obj.get("price"),
            "total_available": obj.get("total_available"),
            "total_capacity": obj.get("total_capacity")
        })
        return _obj


