# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SeatgeekAvailableDetailedWithUpdateSchema(BaseModel):
    """
    SeatgeekAvailableDetailedWithUpdateSchema
    """ # noqa: E501
    listing_id: StrictStr
    section: Optional[StrictStr] = None
    row: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    row_rank: Optional[StrictInt] = None
    seat: Optional[StrictStr] = None
    seat_rank: Optional[StrictInt] = None
    quantity: Optional[StrictInt] = 1
    ticket_price: Optional[StrictStr] = None
    fee: Optional[StrictStr] = None
    total_price: Optional[StrictStr] = None
    deal_score: Optional[StrictStr] = None
    delivery_type: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    inserted: Optional[datetime] = None
    prev_updated: Optional[datetime] = None
    update_reason: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["listing_id", "section", "row", "slug", "row_rank", "seat", "seat_rank", "quantity", "ticket_price", "fee", "total_price", "deal_score", "delivery_type", "notes", "description", "inserted", "prev_updated", "update_reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SeatgeekAvailableDetailedWithUpdateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if section (nullable) is None
        # and model_fields_set contains the field
        if self.section is None and "section" in self.model_fields_set:
            _dict['section'] = None

        # set to None if row (nullable) is None
        # and model_fields_set contains the field
        if self.row is None and "row" in self.model_fields_set:
            _dict['row'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if row_rank (nullable) is None
        # and model_fields_set contains the field
        if self.row_rank is None and "row_rank" in self.model_fields_set:
            _dict['row_rank'] = None

        # set to None if seat (nullable) is None
        # and model_fields_set contains the field
        if self.seat is None and "seat" in self.model_fields_set:
            _dict['seat'] = None

        # set to None if seat_rank (nullable) is None
        # and model_fields_set contains the field
        if self.seat_rank is None and "seat_rank" in self.model_fields_set:
            _dict['seat_rank'] = None

        # set to None if ticket_price (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_price is None and "ticket_price" in self.model_fields_set:
            _dict['ticket_price'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        # set to None if deal_score (nullable) is None
        # and model_fields_set contains the field
        if self.deal_score is None and "deal_score" in self.model_fields_set:
            _dict['deal_score'] = None

        # set to None if delivery_type (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_type is None and "delivery_type" in self.model_fields_set:
            _dict['delivery_type'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if inserted (nullable) is None
        # and model_fields_set contains the field
        if self.inserted is None and "inserted" in self.model_fields_set:
            _dict['inserted'] = None

        # set to None if prev_updated (nullable) is None
        # and model_fields_set contains the field
        if self.prev_updated is None and "prev_updated" in self.model_fields_set:
            _dict['prev_updated'] = None

        # set to None if update_reason (nullable) is None
        # and model_fields_set contains the field
        if self.update_reason is None and "update_reason" in self.model_fields_set:
            _dict['update_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SeatgeekAvailableDetailedWithUpdateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "listing_id": obj.get("listing_id"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "slug": obj.get("slug"),
            "row_rank": obj.get("row_rank"),
            "seat": obj.get("seat"),
            "seat_rank": obj.get("seat_rank"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "ticket_price": obj.get("ticket_price"),
            "fee": obj.get("fee"),
            "total_price": obj.get("total_price"),
            "deal_score": obj.get("deal_score"),
            "delivery_type": obj.get("delivery_type"),
            "notes": obj.get("notes"),
            "description": obj.get("description"),
            "inserted": obj.get("inserted"),
            "prev_updated": obj.get("prev_updated"),
            "update_reason": obj.get("update_reason")
        })
        return _obj


