# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.available_info import AvailableInfo
from listing_data_storage_client.models.pagination_schema import PaginationSchema
from listing_data_storage_client.models.stubhub_available_schema import StubhubAvailableSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StubhubAvailableResponseSchema(BaseModel):
    """
    StubhubAvailableResponseSchema
    """ # noqa: E501
    pagination: PaginationSchema
    info: AvailableInfo
    available_data: Optional[List[StubhubAvailableSchema]] = None
    __properties: ClassVar[List[str]] = ["pagination", "info", "available_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StubhubAvailableResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of info
        if self.info:
            _dict['info'] = self.info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in available_data (list)
        _items = []
        if self.available_data:
            for _item_available_data in self.available_data:
                if _item_available_data:
                    _items.append(_item_available_data.to_dict())
            _dict['available_data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StubhubAvailableResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pagination": PaginationSchema.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None,
            "info": AvailableInfo.from_dict(obj["info"]) if obj.get("info") is not None else None,
            "available_data": [StubhubAvailableSchema.from_dict(_item) for _item in obj["available_data"]] if obj.get("available_data") is not None else None
        })
        return _obj


