# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.stubhub_price_store_schema import StubhubPriceStoreSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StubhubUpdateSeatStoreSchema(BaseModel):
    """
    StubhubUpdateSeatStoreSchema
    """ # noqa: E501
    add_place: List[StubhubPriceStoreSchema]
    remove_place: List[StrictStr]
    update_place: List[StubhubPriceStoreSchema]
    update_info: Optional[List[Any]] = Field(default=None, alias="updateInfo")
    empty_event: StrictBool
    __properties: ClassVar[List[str]] = ["add_place", "remove_place", "update_place", "updateInfo", "empty_event"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StubhubUpdateSeatStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in add_place (list)
        _items = []
        if self.add_place:
            for _item_add_place in self.add_place:
                if _item_add_place:
                    _items.append(_item_add_place.to_dict())
            _dict['add_place'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in update_place (list)
        _items = []
        if self.update_place:
            for _item_update_place in self.update_place:
                if _item_update_place:
                    _items.append(_item_update_place.to_dict())
            _dict['update_place'] = _items
        # set to None if update_info (nullable) is None
        # and model_fields_set contains the field
        if self.update_info is None and "update_info" in self.model_fields_set:
            _dict['updateInfo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StubhubUpdateSeatStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "add_place": [StubhubPriceStoreSchema.from_dict(_item) for _item in obj["add_place"]] if obj.get("add_place") is not None else None,
            "remove_place": obj.get("remove_place"),
            "update_place": [StubhubPriceStoreSchema.from_dict(_item) for _item in obj["update_place"]] if obj.get("update_place") is not None else None,
            "updateInfo": obj.get("updateInfo"),
            "empty_event": obj.get("empty_event")
        })
        return _obj


