# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StubhubUpdateItemSchema(str, Enum):
    """
    StubhubUpdateItemSchema
    """

    """
    allowed enum values
    """
    PRICE = 'price'
    AVAILABLE_TICKETS = 'available_tickets'
    AVAILABLE_QUANTITIES = 'available_quantities'
    TICKET_CLASS_NAME = 'ticket_class_name'
    MAX_QUANTITY = 'max_quantity'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StubhubUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


