# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.base_price1 import BasePrice1
from listing_data_storage_client.models.fees1 import Fees1
from listing_data_storage_client.models.total_price2 import TotalPrice2
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TelechargeStoreSchema(BaseModel):
    """
    TelechargeStoreSchema
    """ # noqa: E501
    place_id: StrictStr = Field(description="SeatId from Telecharge")
    section: StrictStr = Field(description="AreaName: Orchestra, Mezzanine, etc.")
    section_code: StrictStr = Field(description="AreaCode: ORCHC, ORCHO, etc.")
    section_parsed: StrictStr = Field(description="Smart parsed section: Orchestra Center, Orchestra Left, etc.")
    row: StrictStr = Field(description="Row letter/number from SeatId")
    row_rank: StrictInt = Field(description="Row rank (0 = closest to stage)")
    seat_number: StrictStr = Field(description="Seat number from SeatId")
    seat_index: StrictInt = Field(description="Physical seat position index within section+row")
    seat_status: Optional[StrictStr] = Field(default='available', description="Seat availability (always 'available')")
    attributes: StrictStr = Field(description="Comma-separated attributes: Premium, Wheelchair, etc.")
    description: StrictStr = Field(description="Seat/zone messages")
    price_code: Optional[StrictStr] = None
    marketing_code: Optional[StrictStr] = None
    base_price: BasePrice1
    fees: Fees1
    total_price: TotalPrice2
    __properties: ClassVar[List[str]] = ["place_id", "section", "section_code", "section_parsed", "row", "row_rank", "seat_number", "seat_index", "seat_status", "attributes", "description", "price_code", "marketing_code", "base_price", "fees", "total_price"]

    @field_validator('seat_status')
    def seat_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['available']):
            raise ValueError("must be one of enum values ('available')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TelechargeStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_price
        if self.base_price:
            _dict['base_price'] = self.base_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fees
        if self.fees:
            _dict['fees'] = self.fees.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # set to None if price_code (nullable) is None
        # and model_fields_set contains the field
        if self.price_code is None and "price_code" in self.model_fields_set:
            _dict['price_code'] = None

        # set to None if marketing_code (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_code is None and "marketing_code" in self.model_fields_set:
            _dict['marketing_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TelechargeStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "section": obj.get("section"),
            "section_code": obj.get("section_code"),
            "section_parsed": obj.get("section_parsed"),
            "row": obj.get("row"),
            "row_rank": obj.get("row_rank"),
            "seat_number": obj.get("seat_number"),
            "seat_index": obj.get("seat_index"),
            "seat_status": obj.get("seat_status") if obj.get("seat_status") is not None else 'available',
            "attributes": obj.get("attributes"),
            "description": obj.get("description"),
            "price_code": obj.get("price_code"),
            "marketing_code": obj.get("marketing_code"),
            "base_price": BasePrice1.from_dict(obj["base_price"]) if obj.get("base_price") is not None else None,
            "fees": Fees1.from_dict(obj["fees"]) if obj.get("fees") is not None else None,
            "total_price": TotalPrice2.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None
        })
        return _obj


