# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TelechargeAvailablePricesSchema(BaseModel):
    """
    TelechargeAvailablePricesSchema
    """ # noqa: E501
    place_id: StrictStr
    total_price: StrictStr
    base_price: StrictStr
    fees: StrictStr
    section_code: StrictStr
    seat_status: StrictStr
    section: StrictStr
    row: StrictStr
    row_rank: StrictInt
    seat_number: StrictStr
    seat_index: StrictInt
    attributes: StrictStr
    description: StrictStr
    price_code: Optional[StrictStr]
    marketing_code: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["place_id", "total_price", "base_price", "fees", "section_code", "seat_status", "section", "row", "row_rank", "seat_number", "seat_index", "attributes", "description", "price_code", "marketing_code"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TelechargeAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price_code (nullable) is None
        # and model_fields_set contains the field
        if self.price_code is None and "price_code" in self.model_fields_set:
            _dict['price_code'] = None

        # set to None if marketing_code (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_code is None and "marketing_code" in self.model_fields_set:
            _dict['marketing_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TelechargeAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "total_price": obj.get("total_price"),
            "base_price": obj.get("base_price"),
            "fees": obj.get("fees"),
            "section_code": obj.get("section_code"),
            "seat_status": obj.get("seat_status"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "row_rank": obj.get("row_rank"),
            "seat_number": obj.get("seat_number"),
            "seat_index": obj.get("seat_index"),
            "attributes": obj.get("attributes"),
            "description": obj.get("description"),
            "price_code": obj.get("price_code"),
            "marketing_code": obj.get("marketing_code")
        })
        return _obj


