# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TickpickUpdateItemSchema(str, Enum):
    """
    TickpickUpdateItemSchema
    """

    """
    allowed enum values
    """
    PRICE = 'PRICE'
    SUBTOTAL_VALUE = 'SUBTOTAL_VALUE'
    DISPLAYED_VALUE = 'DISPLAYED_VALUE'
    FACE_VALUE = 'FACE_VALUE'
    QUANTITY = 'QUANTITY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TickpickUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


