# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TicketmasterNewInventoryGroupSchema(BaseModel):
    """
    TicketmasterNewInventoryGroupSchema
    """ # noqa: E501
    full_section: Optional[StrictStr]
    section: Optional[StrictStr]
    row: Optional[StrictStr]
    seats: Dict[str, Any]
    quantity: Annotated[int, Field(strict=True, ge=0)]
    protected: Optional[StrictBool]
    list_price: StrictStr
    total_price: StrictStr
    row_rank: Optional[Annotated[int, Field(strict=True, ge=0)]]
    seat_rank: Optional[Annotated[int, Field(strict=True, ge=0)]]
    offer_name: Optional[StrictStr]
    description: List[StrictStr]
    added_time: datetime
    __properties: ClassVar[List[str]] = ["full_section", "section", "row", "seats", "quantity", "protected", "list_price", "total_price", "row_rank", "seat_rank", "offer_name", "description", "added_time"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TicketmasterNewInventoryGroupSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if full_section (nullable) is None
        # and model_fields_set contains the field
        if self.full_section is None and "full_section" in self.model_fields_set:
            _dict['full_section'] = None

        # set to None if section (nullable) is None
        # and model_fields_set contains the field
        if self.section is None and "section" in self.model_fields_set:
            _dict['section'] = None

        # set to None if row (nullable) is None
        # and model_fields_set contains the field
        if self.row is None and "row" in self.model_fields_set:
            _dict['row'] = None

        # set to None if protected (nullable) is None
        # and model_fields_set contains the field
        if self.protected is None and "protected" in self.model_fields_set:
            _dict['protected'] = None

        # set to None if row_rank (nullable) is None
        # and model_fields_set contains the field
        if self.row_rank is None and "row_rank" in self.model_fields_set:
            _dict['row_rank'] = None

        # set to None if seat_rank (nullable) is None
        # and model_fields_set contains the field
        if self.seat_rank is None and "seat_rank" in self.model_fields_set:
            _dict['seat_rank'] = None

        # set to None if offer_name (nullable) is None
        # and model_fields_set contains the field
        if self.offer_name is None and "offer_name" in self.model_fields_set:
            _dict['offer_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TicketmasterNewInventoryGroupSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "full_section": obj.get("full_section"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seats": obj.get("seats"),
            "quantity": obj.get("quantity"),
            "protected": obj.get("protected"),
            "list_price": obj.get("list_price"),
            "total_price": obj.get("total_price"),
            "row_rank": obj.get("row_rank"),
            "seat_rank": obj.get("seat_rank"),
            "offer_name": obj.get("offer_name"),
            "description": obj.get("description"),
            "added_time": obj.get("added_time")
        })
        return _obj


