# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TickpickAvailablePricesSchema(BaseModel):
    """
    TickpickAvailablePricesSchema
    """ # noqa: E501
    place_id: StrictStr
    price: StrictStr
    subtotal_value: Optional[StrictStr]
    displayed_value: Optional[StrictStr]
    face_value: Optional[StrictStr]
    quantity: StrictInt
    __properties: ClassVar[List[str]] = ["place_id", "price", "subtotal_value", "displayed_value", "face_value", "quantity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TickpickAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subtotal_value (nullable) is None
        # and model_fields_set contains the field
        if self.subtotal_value is None and "subtotal_value" in self.model_fields_set:
            _dict['subtotal_value'] = None

        # set to None if displayed_value (nullable) is None
        # and model_fields_set contains the field
        if self.displayed_value is None and "displayed_value" in self.model_fields_set:
            _dict['displayed_value'] = None

        # set to None if face_value (nullable) is None
        # and model_fields_set contains the field
        if self.face_value is None and "face_value" in self.model_fields_set:
            _dict['face_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TickpickAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "price": obj.get("price"),
            "subtotal_value": obj.get("subtotal_value"),
            "displayed_value": obj.get("displayed_value"),
            "face_value": obj.get("face_value"),
            "quantity": obj.get("quantity")
        })
        return _obj


