# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TicketmasterAvailableGaDetailedSchema(BaseModel):
    """
    TicketmasterAvailableGaDetailedSchema
    """ # noqa: E501
    place_id: StrictStr
    full_section: Optional[StrictStr]
    section: StrictStr
    row: StrictStr
    count: Optional[Annotated[int, Field(strict=True, ge=0)]]
    attributes: List[StrictStr]
    offer_name: Optional[StrictStr]
    description: List[StrictStr]
    inventory_type: Optional[StrictStr]
    protected: Optional[StrictBool]
    list_price: Optional[StrictStr]
    total_price: Optional[StrictStr]
    inserted: datetime
    __properties: ClassVar[List[str]] = ["place_id", "full_section", "section", "row", "count", "attributes", "offer_name", "description", "inventory_type", "protected", "list_price", "total_price", "inserted"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TicketmasterAvailableGaDetailedSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if full_section (nullable) is None
        # and model_fields_set contains the field
        if self.full_section is None and "full_section" in self.model_fields_set:
            _dict['full_section'] = None

        # set to None if count (nullable) is None
        # and model_fields_set contains the field
        if self.count is None and "count" in self.model_fields_set:
            _dict['count'] = None

        # set to None if offer_name (nullable) is None
        # and model_fields_set contains the field
        if self.offer_name is None and "offer_name" in self.model_fields_set:
            _dict['offer_name'] = None

        # set to None if inventory_type (nullable) is None
        # and model_fields_set contains the field
        if self.inventory_type is None and "inventory_type" in self.model_fields_set:
            _dict['inventory_type'] = None

        # set to None if protected (nullable) is None
        # and model_fields_set contains the field
        if self.protected is None and "protected" in self.model_fields_set:
            _dict['protected'] = None

        # set to None if list_price (nullable) is None
        # and model_fields_set contains the field
        if self.list_price is None and "list_price" in self.model_fields_set:
            _dict['list_price'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TicketmasterAvailableGaDetailedSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "full_section": obj.get("full_section"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "count": obj.get("count"),
            "attributes": obj.get("attributes"),
            "offer_name": obj.get("offer_name"),
            "description": obj.get("description"),
            "inventory_type": obj.get("inventory_type"),
            "protected": obj.get("protected"),
            "list_price": obj.get("list_price"),
            "total_price": obj.get("total_price"),
            "inserted": obj.get("inserted")
        })
        return _obj


