# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TicketmasterUpdateItemSchema(str, Enum):
    """
    TicketmasterUpdateItemSchema
    """

    """
    allowed enum values
    """
    LIST_PRICE = 'LIST_PRICE'
    TOTAL_PRICE = 'TOTAL_PRICE'
    OFFER_ID = 'OFFER_ID'
    OFFER_NAME = 'OFFER_NAME'
    SELLABLE_QUANTITIES = 'SELLABLE_QUANTITIES'
    PROTECTED = 'PROTECTED'
    INVENTORY_TYPE = 'INVENTORY_TYPE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TicketmasterUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


