# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TicketmasterAvailablePricesSchema(BaseModel):
    """
    TicketmasterAvailablePricesSchema
    """ # noqa: E501
    place_id: StrictStr
    listing_price: StrictStr
    total_price: StrictStr
    offer_id: Optional[StrictStr]
    offer_name: Optional[StrictStr] = None
    sellable_quantities: Optional[List[StrictInt]] = None
    protected: Optional[StrictBool] = None
    inventory_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["place_id", "listing_price", "total_price", "offer_id", "offer_name", "sellable_quantities", "protected", "inventory_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TicketmasterAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if offer_id (nullable) is None
        # and model_fields_set contains the field
        if self.offer_id is None and "offer_id" in self.model_fields_set:
            _dict['offer_id'] = None

        # set to None if offer_name (nullable) is None
        # and model_fields_set contains the field
        if self.offer_name is None and "offer_name" in self.model_fields_set:
            _dict['offer_name'] = None

        # set to None if sellable_quantities (nullable) is None
        # and model_fields_set contains the field
        if self.sellable_quantities is None and "sellable_quantities" in self.model_fields_set:
            _dict['sellable_quantities'] = None

        # set to None if protected (nullable) is None
        # and model_fields_set contains the field
        if self.protected is None and "protected" in self.model_fields_set:
            _dict['protected'] = None

        # set to None if inventory_type (nullable) is None
        # and model_fields_set contains the field
        if self.inventory_type is None and "inventory_type" in self.model_fields_set:
            _dict['inventory_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TicketmasterAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "listing_price": obj.get("listing_price"),
            "total_price": obj.get("total_price"),
            "offer_id": obj.get("offer_id"),
            "offer_name": obj.get("offer_name"),
            "sellable_quantities": obj.get("sellable_quantities"),
            "protected": obj.get("protected"),
            "inventory_type": obj.get("inventory_type")
        })
        return _obj


