# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.displayed_value import DisplayedValue
from listing_data_storage_client.models.face_value import FaceValue
from listing_data_storage_client.models.price1 import Price1
from listing_data_storage_client.models.subtotal_value import SubtotalValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TickpickStoreSchema(BaseModel):
    """
    TickpickStoreSchema
    """ # noqa: E501
    place_id: StrictStr
    subtotal_value: Optional[SubtotalValue] = None
    displayed_value: Optional[DisplayedValue] = None
    face_value: Optional[FaceValue] = None
    price: Price1
    quantity: StrictInt
    section: StrictStr
    row: StrictStr
    notes: StrictStr
    seat_from: Optional[StrictStr]
    seat_to: Optional[StrictStr]
    ticket_type: StrictStr
    split_purchase_options: List[StrictInt]
    __properties: ClassVar[List[str]] = ["place_id", "subtotal_value", "displayed_value", "face_value", "price", "quantity", "section", "row", "notes", "seat_from", "seat_to", "ticket_type", "split_purchase_options"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TickpickStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subtotal_value
        if self.subtotal_value:
            _dict['subtotal_value'] = self.subtotal_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of displayed_value
        if self.displayed_value:
            _dict['displayed_value'] = self.displayed_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of face_value
        if self.face_value:
            _dict['face_value'] = self.face_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # set to None if subtotal_value (nullable) is None
        # and model_fields_set contains the field
        if self.subtotal_value is None and "subtotal_value" in self.model_fields_set:
            _dict['subtotal_value'] = None

        # set to None if displayed_value (nullable) is None
        # and model_fields_set contains the field
        if self.displayed_value is None and "displayed_value" in self.model_fields_set:
            _dict['displayed_value'] = None

        # set to None if face_value (nullable) is None
        # and model_fields_set contains the field
        if self.face_value is None and "face_value" in self.model_fields_set:
            _dict['face_value'] = None

        # set to None if seat_from (nullable) is None
        # and model_fields_set contains the field
        if self.seat_from is None and "seat_from" in self.model_fields_set:
            _dict['seat_from'] = None

        # set to None if seat_to (nullable) is None
        # and model_fields_set contains the field
        if self.seat_to is None and "seat_to" in self.model_fields_set:
            _dict['seat_to'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TickpickStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "subtotal_value": SubtotalValue.from_dict(obj["subtotal_value"]) if obj.get("subtotal_value") is not None else None,
            "displayed_value": DisplayedValue.from_dict(obj["displayed_value"]) if obj.get("displayed_value") is not None else None,
            "face_value": FaceValue.from_dict(obj["face_value"]) if obj.get("face_value") is not None else None,
            "price": Price1.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "quantity": obj.get("quantity"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "notes": obj.get("notes"),
            "seat_from": obj.get("seat_from"),
            "seat_to": obj.get("seat_to"),
            "ticket_type": obj.get("ticket_type"),
            "split_purchase_options": obj.get("split_purchase_options")
        })
        return _obj


