# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.fee1 import Fee1
from listing_data_storage_client.models.ticket_price1 import TicketPrice1
from listing_data_storage_client.models.total_price1 import TotalPrice1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TixrStoreSchema(BaseModel):
    """
    TixrStoreSchema
    """ # noqa: E501
    place_id: StrictStr
    object_type: StrictStr
    section: StrictStr
    row: StrictStr
    seat: StrictStr
    row_rank: Optional[StrictInt] = 0
    seat_rank: Optional[StrictInt] = 0
    quantity: Optional[StrictInt] = 1
    ticket_price: TicketPrice1
    fee: Fee1
    total_price: TotalPrice1
    currency: StrictStr
    price_variant_name: Optional[StrictStr] = None
    delivery_type: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    category_label: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["place_id", "object_type", "section", "row", "seat", "row_rank", "seat_rank", "quantity", "ticket_price", "fee", "total_price", "currency", "price_variant_name", "delivery_type", "notes", "description", "category_label"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TixrStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ticket_price
        if self.ticket_price:
            _dict['ticket_price'] = self.ticket_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fee
        if self.fee:
            _dict['fee'] = self.fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # set to None if price_variant_name (nullable) is None
        # and model_fields_set contains the field
        if self.price_variant_name is None and "price_variant_name" in self.model_fields_set:
            _dict['price_variant_name'] = None

        # set to None if delivery_type (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_type is None and "delivery_type" in self.model_fields_set:
            _dict['delivery_type'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if category_label (nullable) is None
        # and model_fields_set contains the field
        if self.category_label is None and "category_label" in self.model_fields_set:
            _dict['category_label'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TixrStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "object_type": obj.get("object_type"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seat": obj.get("seat"),
            "row_rank": obj.get("row_rank") if obj.get("row_rank") is not None else 0,
            "seat_rank": obj.get("seat_rank") if obj.get("seat_rank") is not None else 0,
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "ticket_price": TicketPrice1.from_dict(obj["ticket_price"]) if obj.get("ticket_price") is not None else None,
            "fee": Fee1.from_dict(obj["fee"]) if obj.get("fee") is not None else None,
            "total_price": TotalPrice1.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None,
            "currency": obj.get("currency"),
            "price_variant_name": obj.get("price_variant_name"),
            "delivery_type": obj.get("delivery_type"),
            "notes": obj.get("notes"),
            "description": obj.get("description"),
            "category_label": obj.get("category_label")
        })
        return _obj


