# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TixrUpdateItemSchema(str, Enum):
    """
    TixrUpdateItemSchema
    """

    """
    allowed enum values
    """
    TICKET_PRICE = 'TICKET_PRICE'
    FEE = 'FEE'
    TOTAL_PRICE = 'TOTAL_PRICE'
    CURRENCY = 'CURRENCY'
    PRICE_VARIANT_NAME = 'PRICE_VARIANT_NAME'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TixrUpdateItemSchema from a JSON string"""
        return cls(json.loads(json_str))


