# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TixrAvailablePricesSchema(BaseModel):
    """
    TixrAvailablePricesSchema
    """ # noqa: E501
    place_id: StrictStr
    ticket_price: StrictStr
    fee: StrictStr
    total_price: StrictStr
    currency: StrictStr
    price_variant_name: Optional[StrictStr]
    section: StrictStr
    row: StrictStr
    seat: StrictStr
    row_rank: StrictInt
    seat_rank: StrictInt
    object_type: StrictStr
    quantity: StrictInt
    delivery_type: Optional[StrictStr]
    notes: Optional[StrictStr]
    description: Optional[StrictStr]
    category_label: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["place_id", "ticket_price", "fee", "total_price", "currency", "price_variant_name", "section", "row", "seat", "row_rank", "seat_rank", "object_type", "quantity", "delivery_type", "notes", "description", "category_label"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TixrAvailablePricesSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price_variant_name (nullable) is None
        # and model_fields_set contains the field
        if self.price_variant_name is None and "price_variant_name" in self.model_fields_set:
            _dict['price_variant_name'] = None

        # set to None if delivery_type (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_type is None and "delivery_type" in self.model_fields_set:
            _dict['delivery_type'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if category_label (nullable) is None
        # and model_fields_set contains the field
        if self.category_label is None and "category_label" in self.model_fields_set:
            _dict['category_label'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TixrAvailablePricesSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "ticket_price": obj.get("ticket_price"),
            "fee": obj.get("fee"),
            "total_price": obj.get("total_price"),
            "currency": obj.get("currency"),
            "price_variant_name": obj.get("price_variant_name"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "seat": obj.get("seat"),
            "row_rank": obj.get("row_rank"),
            "seat_rank": obj.get("seat_rank"),
            "object_type": obj.get("object_type"),
            "quantity": obj.get("quantity"),
            "delivery_type": obj.get("delivery_type"),
            "notes": obj.get("notes"),
            "description": obj.get("description"),
            "category_label": obj.get("category_label")
        })
        return _obj


