# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from listing_data_storage_client.models.fee import Fee
from listing_data_storage_client.models.ticket_price import TicketPrice
from listing_data_storage_client.models.total_price import TotalPrice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TixrPriceStoreSchema(BaseModel):
    """
    TixrPriceStoreSchema
    """ # noqa: E501
    place_id: StrictStr
    ticket_price: Optional[TicketPrice] = None
    fee: Optional[Fee] = None
    total_price: Optional[TotalPrice] = None
    currency: Optional[StrictStr] = None
    price_variant_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["place_id", "ticket_price", "fee", "total_price", "currency", "price_variant_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TixrPriceStoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ticket_price
        if self.ticket_price:
            _dict['ticket_price'] = self.ticket_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fee
        if self.fee:
            _dict['fee'] = self.fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # set to None if ticket_price (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_price is None and "ticket_price" in self.model_fields_set:
            _dict['ticket_price'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if price_variant_name (nullable) is None
        # and model_fields_set contains the field
        if self.price_variant_name is None and "price_variant_name" in self.model_fields_set:
            _dict['price_variant_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TixrPriceStoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "ticket_price": TicketPrice.from_dict(obj["ticket_price"]) if obj.get("ticket_price") is not None else None,
            "fee": Fee.from_dict(obj["fee"]) if obj.get("fee") is not None else None,
            "total_price": TotalPrice.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None,
            "currency": obj.get("currency"),
            "price_variant_name": obj.get("price_variant_name")
        })
        return _obj


