# coding: utf-8

"""
    Listing Data Storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VividseatsAvailableSchema(BaseModel):
    """
    VividseatsAvailableSchema
    """ # noqa: E501
    place_id: StrictStr
    section: StrictStr
    row: StrictStr
    price: Optional[StrictStr]
    notes: Optional[StrictStr]
    inserted: datetime
    updated: Optional[datetime]
    quantity: Optional[Annotated[int, Field(strict=True, ge=0)]]
    sellable_quantities: Optional[List[StrictInt]]
    section_code: Optional[StrictStr]
    section_grouping_code: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["place_id", "section", "row", "price", "notes", "inserted", "updated", "quantity", "sellable_quantities", "section_code", "section_grouping_code"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VividseatsAvailableSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if updated (nullable) is None
        # and model_fields_set contains the field
        if self.updated is None and "updated" in self.model_fields_set:
            _dict['updated'] = None

        # set to None if quantity (nullable) is None
        # and model_fields_set contains the field
        if self.quantity is None and "quantity" in self.model_fields_set:
            _dict['quantity'] = None

        # set to None if sellable_quantities (nullable) is None
        # and model_fields_set contains the field
        if self.sellable_quantities is None and "sellable_quantities" in self.model_fields_set:
            _dict['sellable_quantities'] = None

        # set to None if section_code (nullable) is None
        # and model_fields_set contains the field
        if self.section_code is None and "section_code" in self.model_fields_set:
            _dict['section_code'] = None

        # set to None if section_grouping_code (nullable) is None
        # and model_fields_set contains the field
        if self.section_grouping_code is None and "section_grouping_code" in self.model_fields_set:
            _dict['section_grouping_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VividseatsAvailableSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "place_id": obj.get("place_id"),
            "section": obj.get("section"),
            "row": obj.get("row"),
            "price": obj.get("price"),
            "notes": obj.get("notes"),
            "inserted": obj.get("inserted"),
            "updated": obj.get("updated"),
            "quantity": obj.get("quantity"),
            "sellable_quantities": obj.get("sellable_quantities"),
            "section_code": obj.get("section_code"),
            "section_grouping_code": obj.get("section_grouping_code")
        })
        return _obj


